# Generated by Django 2.1.10 on 2019-07-17 15:04

import SiteSpace.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categories', djongo.models.fields.ArrayModelField(model_container=SiteSpace.models.Category)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('variants', djongo.models.fields.ArrayModelField(model_container=SiteSpace.models.Variant)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('variant_type', models.CharField(max_length=255)),
            ],
        ),
    ]
